### ISSUE TITLE
Unrecognized attribute string flag '?' in attribute string "T@"NSString",?,R,C" for property debugDescription

### ISSUE THREAD

**Issue by drewsterb** [mcgaritydotme/shortcuts#1]
I saw a comment about this error message in the README.

Any idea what's causing it?  I'm seeing it elsewhere and haven't been able to narrow it down.

Thanks!! 😀

**Comment by mcgaritydotme** [comment]
@drewsterb I do not — as mentioned, it's likely an OS bug. The scant information I've found shows that is what others also think:

* https://routinehub.co/shortcut/10038/
* https://github.com/electrikmilk/cherri/issues/49

There's apparently a workaround that involves setting up a private signing server or signing them on an iOS device.
